import { Post, Store, Message, ChatMessage, OrderItem, RankingUser, Profile } from './types'

export const mockPosts: Post[] = [
  {
    id: 'p1',
    userId: 'u2',
    nickname: 'さくら',
    age: 24,
    prefecture: '東京都',
    targetPrefecture: ['東京都', '神奈川県'],
    content: '今夜J新宿に初めて行きます！どんな雰囲気か楽しみ😊 どなたかいれば声かけてください',
    likes: 12,
    createdAt: '2026-06-28T18:30:00Z',
    liked: false,
  },
  {
    id: 'p2',
    userId: 'u3',
    nickname: 'たける',
    age: 28,
    prefecture: '大阪府',
    targetPrefecture: ['大阪府', '兵庫県', '京都府'],
    content: 'J梅田常連です。今週末も行く予定。気軽に話しかけてもらえると嬉しいです！',
    likes: 8,
    createdAt: '2026-06-28T17:00:00Z',
    liked: true,
  },
  {
    id: 'p3',
    userId: 'u4',
    nickname: 'みゆき',
    age: 26,
    prefecture: '福岡県',
    targetPrefecture: ['福岡県'],
    content: 'J福岡行ってきました！スタッフさんめちゃ親切で最高でした✨また絶対行きます',
    likes: 21,
    createdAt: '2026-06-28T15:45:00Z',
    liked: false,
  },
  {
    id: 'p4',
    userId: 'u5',
    nickname: 'ゆうすけ',
    age: 31,
    prefecture: '北海道',
    targetPrefecture: ['北海道'],
    content: 'J札幌のボトルキープしました！次来るとき楽しみ。一人で来てる人ぜひ話しましょう',
    likes: 5,
    createdAt: '2026-06-28T14:00:00Z',
    liked: false,
  },
  {
    id: 'p5',
    userId: 'u6',
    nickname: 'あいこ',
    age: 22,
    prefecture: '熊本県',
    targetPrefecture: ['熊本県', '福岡県'],
    content: '先週J熊本デビューしました！緊張したけど楽しかった〜。また行きたいな',
    likes: 17,
    createdAt: '2026-06-28T12:30:00Z',
    liked: false,
  },
  {
    id: 'p6',
    userId: 'u7',
    nickname: 'けんじ',
    age: 35,
    prefecture: '東京都',
    targetPrefecture: ['東京都', '埼玉県', '千葉県'],
    content: 'J西新宿とJ新宿両方行ったことあります。雰囲気違って面白い。どちらもオススメ！',
    likes: 9,
    createdAt: '2026-06-28T10:00:00Z',
    liked: true,
  },
]

export const mockStores: Store[] = [
  { id: 's1', name: 'J札幌', nameEn: 'J-Sapporo', male: 7, female: 12, total: 19, isFavorite: false },
  { id: 's2', name: 'J新宿', nameEn: 'J-Shinjuku', male: 15, female: 22, total: 37, isFavorite: true },
  { id: 's3', name: 'J西新宿', nameEn: 'J-Nishi-Shinjuku', male: 9, female: 18, total: 27, isFavorite: false },
  { id: 's4', name: 'J茶屋町', nameEn: 'J-Chayamachi', male: 11, female: 20, total: 31, isFavorite: false },
  { id: 's5', name: 'J梅田', nameEn: 'J-Umeda', male: 13, female: 25, total: 38, isFavorite: true },
  { id: 's6', name: 'J難波', nameEn: 'J-Namba', male: 6, female: 14, total: 20, isFavorite: false },
  { id: 's7', name: 'J福岡', nameEn: 'J-Fukuoka', male: 10, female: 17, total: 27, isFavorite: false },
  { id: 's8', name: 'J熊本', nameEn: 'J-Kumamoto', male: 4, female: 8, total: 12, isFavorite: false },
]

export const mockMessages: Message[] = [
  { id: 'm1', userId: 'u2', nickname: 'さくら', lastMessage: 'よろしくお願いします！', unread: 2, createdAt: '2026-06-28T19:00:00Z' },
  { id: 'm2', userId: 'u3', nickname: 'たける', lastMessage: '今度一緒に行きませんか？', unread: 0, createdAt: '2026-06-28T16:00:00Z' },
  { id: 'm3', userId: 'u4', nickname: 'みゆき', lastMessage: 'ありがとうございました😊', unread: 1, createdAt: '2026-06-27T22:00:00Z' },
  { id: 'm4', userId: 'u6', nickname: 'あいこ', lastMessage: 'また行きましょう！', unread: 0, createdAt: '2026-06-27T20:30:00Z' },
]

export const mockChatMessages: ChatMessage[] = [
  { id: 'c1', senderId: 'u2', content: 'こんにちは！掲示板の投稿見ました', createdAt: '2026-06-28T18:55:00Z' },
  { id: 'c2', senderId: 'me', content: 'はじめまして！コメントありがとうございます', createdAt: '2026-06-28T18:57:00Z' },
  { id: 'c3', senderId: 'u2', content: 'J新宿ってどんな雰囲気ですか？', createdAt: '2026-06-28T18:58:00Z' },
  { id: 'c4', senderId: 'me', content: '落ち着いた雰囲気でスタッフさんも親切ですよ！', createdAt: '2026-06-28T19:00:00Z' },
  { id: 'c5', senderId: 'u2', content: 'よろしくお願いします！', createdAt: '2026-06-28T19:01:00Z' },
]

export const mockMenuItems: OrderItem[] = [
  { id: 'f1', name: '枝豆', price: 380, category: 'フード', description: '塩茹で枝豆' },
  { id: 'f2', name: 'フライドポテト', price: 480, category: 'フード', description: 'サクサクポテト' },
  { id: 'f3', name: 'チーズプレート', price: 680, category: 'フード', description: '盛り合わせ4種' },
  { id: 'f4', name: 'カルパッチョ', price: 780, category: 'フード', description: '本日の鮮魚' },
  { id: 'd1', name: 'ハイボール', price: 550, category: 'ドリンク', description: 'サントリー角ハイボール' },
  { id: 'd2', name: 'レモンサワー', price: 550, category: 'ドリンク', description: '生レモン搾り' },
  { id: 'd3', name: 'カシスオレンジ', price: 600, category: 'ドリンク', description: 'カシスリキュール' },
  { id: 'd4', name: 'ジントニック', price: 600, category: 'ドリンク', description: 'Beefeaterジン' },
  { id: 'b1', name: 'サントリー角', price: 5500, category: 'ボトル', description: '700ml' },
  { id: 'b2', name: 'ジャックダニエル', price: 6500, category: 'ボトル', description: '700ml' },
  { id: 'b3', name: 'アブソルート', price: 6000, category: 'ボトル', description: '700ml ウォッカ' },
  { id: 'ch1', name: 'モエ エ シャンドン', price: 18000, category: 'シャンパン', description: '750ml' },
  { id: 'ch2', name: 'ヴーヴ クリコ', price: 22000, category: 'シャンパン', description: '750ml イエローラベル' },
  { id: 'ch3', name: 'ドン ペリニヨン', price: 55000, category: 'シャンパン', description: '750ml 2013年' },
  { id: 'o1', name: 'ソフトドリンク', price: 300, category: 'その他', description: 'コーラ/ジュース' },
  { id: 'o2', name: 'ミネラルウォーター', price: 200, category: 'その他', description: 'evian 500ml' },
  { id: 'o3', name: 'アイスクリーム', price: 400, category: 'その他', description: 'バニラ/チョコ' },
  { id: 'o4', name: 'おつまみセット', price: 580, category: 'その他', description: '小腹おつまみ詰め合わせ' },
  { id: 'o5', name: 'コーヒー', price: 350, category: 'その他', description: 'ホット/アイス' },
  { id: 'o6', name: 'フルーツプレート', price: 880, category: 'その他', description: '季節のフルーツ盛り合わせ' },
]

export const mockRankingUsers: RankingUser[] = [
  { rank: 1, nickname: 'ゴールドキング', mileage: 12450, memberRank: 'DIAMOND' },
  { rank: 2, nickname: 'たける', mileage: 9830, memberRank: 'DIAMOND' },
  { rank: 3, nickname: 'きらら姫', mileage: 8720, memberRank: 'PLATINUM' },
  { rank: 4, nickname: 'ゆうき', mileage: 7650, memberRank: 'PLATINUM' },
  { rank: 5, nickname: 'みほ', mileage: 6340, memberRank: 'GOLD' },
  { rank: 6, nickname: 'りょうた', mileage: 5890, memberRank: 'GOLD' },
  { rank: 7, nickname: 'なな', mileage: 4560, memberRank: 'SILVER' },
  { rank: 8, nickname: 'しょうへい', mileage: 3210, memberRank: 'SILVER' },
  { rank: 9, nickname: 'あかね', mileage: 2890, memberRank: 'BRONZE' },
  { rank: 10, nickname: 'けんじ', mileage: 2450, memberRank: 'BRONZE' },
]

export const mockCurrentUser: Profile = {
  id: 'me',
  memberId: 'JIS-000123',
  nickname: 'あなた',
  age: 27,
  gender: 'male',
  prefecture: '東京都',
  bio: '相席ラウンジが好きです。気軽に声かけてください！',
  mbti: 'ENFJ',
  job: 'IT',
  height: 170,
  bodyType: '普通',
  rank: 'SILVER',
  mileage: 40,
  rating: 3.2,
  seatingHours: 8,
  photos: [],
}
